# 									
# Demonstrate that isotopes produced in hadronic processes
# can be treated by RadioactiveDecay.  
#
# To register hadronic processes, uncomment corresponding lines
# in PhysicsList.cc
#                                                                         
/control/verbose 2
/run/verbose 1
#
/run/initialize
#
#/process/list
#
/gun/particle neutron 
/gun/energy 14.0 MeV
/gun/position 0. 0. 0.
#
/analysis/setFileName neutron
/analysis/h1/set 1  1000  0. 15 MeV
/analysis/h1/set 2  1000  0. 15 MeV
/analysis/h1/set 3  1000  0. 15 MeV
/analysis/h1/set 4  1000  0. 15 MeV
/analysis/h1/set 5  1000  0. 15 MeV
/analysis/h1/set 6  1000  0. 10 MeV
/analysis/h1/set 7  1000  0. 1 MeV
/analysis/h1/set 8  1000  0. 0.1 MeV
/run/printProgress 1
/run/beamOn 1000000000
